server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: pass
    url: jdbc:mysql://localhost:3306/pfemanager
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true

#  mail:
#    host: localhost
#    port: 1025
#    username: hello
#    password: hello
#
#    properties:
#      mail:
#        smtp:
#          ssl:
#            trust: "*"
#          auth: true
#          starttls:
#            enable: true
#          connectiontimeout: 5000
#          timeout: 3000
#          writetimeout: 5000

application :
  security:
    jwt:
      secret-key : 3e58950f9b875dddf66b25bd1b846e78c8c2bb923ee8cbd7f72695aefb626be3
      expiration : 86400000
      refresh-token :
        expiration : 604800000